// Top-level build file di mana Anda menambahkan opsi konfigurasi umum untuk semua sub-proyek/modul.
plugins {
    id 'com.android.application' version '7.4.0' apply false
    id 'com.android.library' version '7.4.0' apply false
    id 'com.chaquo.python' version '14.0.2' apply false
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
